version: 2.1

jobs:
  build-psycopg-layer:
    docker:
      - image: amazonlinux:2  # Amazon Linux 2 for AWS Lambda compatibility

    steps:
      - checkout  # Checkout repository code

      - run:
          name: Install System Dependencies
          command: |
            yum update -y
            yum install -y gcc python3 python3-devel python3-pip zip tar gzip postgresql-libs postgresql-devel
            python3 -m pip install --upgrade pip

      - run:
          name: Build psycopg Layer
          command: |
            # Create a directory for the layer
            mkdir -p ~/layer/python
            # Install psycopg with its binary distribution into the layer's python folder
            python3 -m pip install "psycopg[binary]" -t ~/layer/python

            # Copy the shared PostgreSQL library needed by psycopg3
            mkdir -p ~/layer/lib
            cp /usr/lib64/libpq.so* ~/layer/lib

            # Package the layer as a ZIP file
            cd ~/layer
            zip -r psycopg-layer.zip python lib

      - persist_to_workspace:
          root: ~/layer
          paths:
            - psycopg-layer.zip  # Persist the ZIP file for later deployment


  terraform-deploy:
    docker:
      - image: hashicorp/terraform:latest  # Use Terraform's official image

    environment:
      AWS_REGION: "us-west-2"  # Ensure the region is set

    steps:
      - checkout  # Checkout the code

      - attach_workspace:
          at: .

      - run:
          name: Set AWS Credentials
          command: |
            export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
            export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
            export AWS_REGION="us-west-2"

      - run:
          name: Terraform Init
          command: terraform init

      - run:
          name: Terraform Plan
          command: terraform plan -out=tfplan

      - run:
          name: Terraform Apply
          command: terraform apply -auto-approve tfplan

workflows:
  build-and-deploy:
    jobs:
      - build-psycopg-layer
      - terraform-deploy:
          requires:
            - build-psycopg-layer  # Terraform runs only after both Lambda Layers are built
