version: 2.1

jobs:
  build-lambda-layer:
    docker:
      - image: amazonlinux:2  # Use Amazon Linux 2 for compatibility

    steps:
      - checkout  # Checkout repository code

      - run:
          name: Install Required Packages
          command: |
            yum install -y gcc python3 python3-devel python3-pip zip
            python3 -m pip install --upgrade pip

      - run:
          name: Install psycopg2 in Layer Directory
          command: |
            mkdir -p python
            python3 -m pip install psycopg2-binary -t python

      - run:
          name: Package Lambda Layer
          command: zip -r psycopg2-layer.zip python

      - run:
          name: Upload Lambda Layer to AWS
          command: |
            aws lambda publish-layer-version \
              --layer-name psycopg2-layer \
              --description "Psycopg2 Lambda Layer for Amazon Linux 2" \
              --zip-file fileb://psycopg2-layer.zip \
              --compatible-runtimes python3.8 python3.9 python3.10 python3.11 \
              --region $AWS_REGION

workflows:
  build-and-deploy:
    jobs:
      - build-lambda-layer
